// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWWtyxXs6DIBE1W-rujt-qzTcysGFQ0B0',
    appId: '1:996519131537:web:15010e0d5e5d17e9dc0230',
    messagingSenderId: '996519131537',
    projectId: 'dalelapp-698a0',
    authDomain: 'dalelapp-698a0.firebaseapp.com',
    storageBucket: 'dalelapp-698a0.appspot.com',
    measurementId: 'G-1HS8DXNJ1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3JCP5XBvTNUMF7M6vvbbsxDFfgHTA4AA',
    appId: '1:996519131537:android:3ef4d65baa92413bdc0230',
    messagingSenderId: '996519131537',
    projectId: 'dalelapp-698a0',
    storageBucket: 'dalelapp-698a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlEgKiPdIfkyXxVNlrGU99pfDB3UhgQ2A',
    appId: '1:996519131537:ios:7014b1d7a0127a8fdc0230',
    messagingSenderId: '996519131537',
    projectId: 'dalelapp-698a0',
    storageBucket: 'dalelapp-698a0.appspot.com',
    iosBundleId: 'com.example.dalelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlEgKiPdIfkyXxVNlrGU99pfDB3UhgQ2A',
    appId: '1:996519131537:ios:dcd387c694753e55dc0230',
    messagingSenderId: '996519131537',
    projectId: 'dalelapp-698a0',
    storageBucket: 'dalelapp-698a0.appspot.com',
    iosBundleId: 'com.example.dalelApp.RunnerTests',
  );
}
